//! App-wide constants.
//!
//! Centralizes the tool name, config paths, environment variable names,
//! and URLs so a rename only requires changing this file.

// ── Version & build metadata ────────────────────────────────────────

/// Semantic version from Cargo.toml (patched from the git tag in CI).
pub const VERSION: &str = env!("CARGO_PKG_VERSION");

/// Full version string including dev metadata.
///
/// For release builds (HEAD tagged `v{VERSION}`) this equals [`VERSION`].
/// For development builds it appends `-dev+{GIT_SHA}` so that telemetry
/// and diagnostics can distinguish local builds from released ones.
pub const FULL_VERSION: &str = env!("FULL_VERSION");

/// Short git commit hash at build time, or `"unknown"`.
pub const GIT_SHA: &str = env!("GIT_SHA");

/// Build date (UTC, `YYYY-MM-DD`), or `"unknown"`.
pub const BUILD_DATE: &str = env!("BUILD_DATE");

/// Compilation target triple (e.g. `x86_64-unknown-linux-gnu`).
pub const TARGET: &str = env!("TARGET");

/// User-Agent header for HTTP requests.
pub const USER_AGENT: &str = concat!("nitpik/", env!("CARGO_PKG_VERSION"));

// ── App identity ────────────────────────────────────────────────────

/// Display name of the tool (lowercase).
pub const APP_NAME: &str = "nitpik";

/// Local config filename (e.g. `.nitpik.toml` in repo root).
pub const CONFIG_FILENAME: &str = ".nitpik.toml";

/// Directory name under `~/.config/` for global config and cache.
pub const CONFIG_DIR: &str = "nitpik";

/// AI-generated content disclosure notice.
pub const AI_DISCLOSURE: &str =
    "Generated by nitpik — AI-powered analysis. Findings are advisory and may contain errors.";

/// Telemetry heartbeat endpoint.
pub const TELEMETRY_URL: &str = "https://nitpik.dev/v1/heartbeat";


// ── GitHub releases (self-update) ───────────────────────────────────

/// GitHub owner/repo for release downloads.
pub const GITHUB_REPO: &str = "nsrosenqvist/nitpik";

/// GitHub API endpoint for the latest release metadata.
pub const GITHUB_RELEASES_LATEST_API: &str =
    "https://api.github.com/repos/nsrosenqvist/nitpik/releases/latest";

/// Build a download URL for a release asset.
pub fn release_asset_url(tag: &str, target: &str) -> String {
    format!(
        "https://github.com/{}/releases/download/{}/nitpik-{}.tar.gz",
        GITHUB_REPO, tag, target
    )
}

/// Build a download URL for the SHA256SUMS file of a release.
pub fn release_checksums_url(tag: &str) -> String {
    format!(
        "https://github.com/{}/releases/download/{}/SHA256SUMS",
        GITHUB_REPO, tag
    )
}

// ── Review context docs ─────────────────────────────────────────────

/// Dedicated review context files that take precedence over generic project docs.
///
/// When any of these exist in the repo root (and are not excluded), only these
/// are included — the generic doc list (`AGENTS.md`, `CONVENTIONS.md`, etc.) is
/// skipped entirely. This lets maintainers provide focused review guidance
/// without polluting the prompt with coding-agent instructions.
pub const PRIORITY_DOC_FILES: &[&str] = &["REVIEW.md", "NITPIK.md"];

// ── Environment variable names ──────────────────────────────────────

pub const ENV_PROVIDER: &str = "NITPIK_PROVIDER";
pub const ENV_MODEL: &str = "NITPIK_MODEL";
pub const ENV_API_KEY: &str = "NITPIK_API_KEY";
pub const ENV_BASE_URL: &str = "NITPIK_BASE_URL";
pub const ENV_LICENSE_KEY: &str = "NITPIK_LICENSE_KEY";
pub const ENV_TELEMETRY: &str = "NITPIK_TELEMETRY";
pub const ENV_DEBUG: &str = "NITPIK_DEBUG";

/// Environment variables stripped from custom command subprocesses.
///
/// These contain LLM API keys and nitpik secrets that spawned commands
/// should never see. Profile authors can explicitly pass through other
/// env vars via the `environment` frontmatter field.
pub const SENSITIVE_ENV_VARS: &[&str] = &[
    // nitpik's own secrets
    ENV_API_KEY,
    ENV_LICENSE_KEY,
    // Provider-specific API keys
    "ANTHROPIC_API_KEY",
    "OPENAI_API_KEY",
    "COHERE_API_KEY",
    "GEMINI_API_KEY",
    "PERPLEXITY_API_KEY",
    "DEEPSEEK_API_KEY",
    "XAI_API_KEY",
    "GROQ_API_KEY",
];
